---
name: Generate & Publish Pages

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 12 * * *"
  push:
    paths:
      - "**.jsonata"
      - ".github/workflows/*.yml"

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  filter:
    name: Filter Release Data
    strategy:
      matrix:
        include:
          - org_repo: kong/kong
            query: >-
              name:^kong$ AND
              repository:^gateway AND
              distribution:el AND
              distribution:9 AND
              architecture:x86_64

          - org_repo: kong/kong-ee
            query: >-
              name:kong-enterprise-edition-fips AND
              repository:^gateway AND
              distribution:el AND
              distribution:9 AND
              architecture:x86_64

          - org_repo: kong/kong-mesh
            query: >-
              name:^kong-mesh-linux-amd64$ AND
              repository:^kong-mesh-binaries-release$

          - org_repo: kong/deck

          - org_repo: kong/kubernetes-ingress-controller

          - org_repo: kumahq/kuma
            query: >-
              name:^kuma-linux-amd64$ AND
              repository:^kuma-binaries-release$

    uses: ./.github/workflows/serialize.yml
    with:
      org_repo: ${{ matrix.org_repo }}
      query: ${{ matrix.query }}
    secrets: inherit

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: filter
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: _site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
