---
name: Generate & Publish Pages

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 12 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

env:
  PAGE_SIZE: 3

jobs:
  serialize:
    runs-on: ubuntu-latest
    name: Serialize Release Data
    # strategy:
    #   matrix:
    #     version:
    #       -
    steps:
      - name: Setup
        run: npm install --global jfq

      - name: Checkout
        uses: actions/checkout@v4

      - name: Kong Gateway
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
          CLOUDSMITH_QUERY: >-
            name:^kong$ AND
            distribution:el AND
            distribution:9 AND
            architecture:x86_64 AND
            repository:^gateway
          VERBOSE: ${{ runner.debug }}
          DIR: kong/kong
        run: |
          [ -n "${VERBOSE:-}" ] && set -x

          mkdir -pv "tmp/${DIR}"

          # --get required for --data* flags to be query params
          curl ${_V:-} --get --location --fail \
            -H 'accept: application/json' \
            -H "X-Api-Key: ${CLOUDSMITH_API_KEY}" \
            --data-urlencode "query=${CLOUDSMITH_QUERY}" \
            --data 'page=1' \
            --data "page_size=$PAGE_SIZE" \
            'https://api.cloudsmith.io/v1/packages/kong/' \
              | jfq -q "${DIR}/query.jsonata" > "tmp/${DIR}/index.html"

      - name: Kong Gateway Enterprise
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
          CLOUDSMITH_QUERY: >-
            name:kong-enterprise-edition-fips AND
            distribution:el AND
            distribution:9 AND
            architecture:x86_64 AND
            repository:^gateway
          VERBOSE: ${{ runner.debug }}
          DIR: kong/kong-ee
        run: |
          [ -n "${VERBOSE:-}" ] && set -x

          mkdir -pv "tmp/${DIR}"

          # --get required for --data* flags to be query params
          curl ${_V:-} --get --location --fail \
            -H 'accept: application/json' \
            -H "X-Api-Key: ${CLOUDSMITH_API_KEY}" \
            --data-urlencode "query=${CLOUDSMITH_QUERY}" \
            --data 'page=1' \
            --data "page_size=$PAGE_SIZE" \
            'https://api.cloudsmith.io/v1/packages/kong/' \
              | jfq -q "${DIR}/query.jsonata" > "tmp/${DIR}/index.html"

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: tmp

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: serialize
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: _site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
